"""add chart model

Revision ID: 2a5f7e680d20
Revises: c1cda2f0042c
Create Date: 2023-06-22 15:36:36.274168

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2a5f7e680d20"
down_revision = "c1cda2f0042c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charts",
        sa.Column("waypointSymbol", sa.String(), nullable=False),
        sa.Column("submittedBy", sa.String(), nullable=False),
        sa.Column("submittedOn", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("waypointSymbol"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("charts")
    # ### end Alembic commands ###
