"""add SystemMappingStatusModel

Revision ID: 565ea3c8cf11
Revises: d520627e2eb3
Create Date: 2023-06-23 10:24:30.418757

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "565ea3c8cf11"
down_revision = "d520627e2eb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "systems_mapping",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column(
            "mapped",
            sa.Enum(
                "UN_MAPPED", "INCOMPLETE", "MAPPED", name="systemmappingmappedenum"
            ),
            nullable=False,
        ),
        sa.Column("ship_symbol", sa.String(), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_systems_mapping_ship_symbol"),
        "systems_mapping",
        ["ship_symbol"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_systems_mapping_ship_symbol"), table_name="systems_mapping")
    op.drop_table("systems_mapping")
    # ### end Alembic commands ###
