"""add survey

Revision ID: c1cda2f0042c
Revises:
Create Date: 2023-06-20 16:13:11.374243

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c1cda2f0042c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "surveys",
        sa.Column("signature", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("deposits", sa.JSON(), nullable=False),
        sa.Column("expiration", sa.String(), nullable=False),
        sa.Column("size", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("signature"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("surveys")
    # ### end Alembic commands ###
